services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8001:8000"
    networks:
      - shared-network

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - shared-network
  
  nginx:
    image: nginx:latest
    container_name: nginxx
    ports:
      - "82:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - shared-network

networks:
  shared-network:
    name: shared-network

