services:
  idm_db:
    image: postgres:13
    container_name: idm_db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: idm_db
    ports:
      - "5433:5432"
    networks:
      - shared-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d idm_db"]
      interval: 5s
      retries: 5
      timeout: 5s

  idm_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idm_service
    ports:
      - "50051:50051"
    environment: 
      - DATABASE_URL=postgresql://user:password@idm_db:5432/idm_db
    depends_on:
      idm_db:
        condition: service_healthy
    networks:
      - shared-network

  idm_api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: idm_api
    ports:
      - "8080:8080"
    depends_on:
      idm_db:
        condition: service_healthy
    networks:
      - shared-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      idm_db:
        condition: service_healthy
    networks:
      - shared-network

volumes:
  db_data:

networks:
  shared-network:
    name: shared-network
